### ISSUE TITLE
Option to choose a template for the file being created

### ISSUE THREAD

**Issue by Gandhi24** [agrawal-d/competitive-programming-helper#15] opened 2020-03-13 20:53 UTC
It'd be great if when a task is parsed and new file is created, instead of a blank file, an existing user specified template appears.

**Comment by agrawal-d** [comment] 2020-03-21 12:31
Duplicate of https://github.com/agrawal-d/competitive-programming-helper/issues/9

**Closed by agrawal-d** 2020-03-21 12:31 UTC
Labels: duplicate
